[[Entities]]
    entityType = "RenderEntity"
    meshNames = ["TriangleMesh"]
    cullMode = "BackFace"
    textureNames = ["BasicTexture"]
    shaderNames = ["EntityVertexShader", "EntityFragmentShader"]

[[Meshes]]
    name = "TriangleMesh"
    filePath = "meshes/viking.obj"

[[Textures]]
    name = "BasicTexture"
    textureType = "ImageFile"
    addressMode = "Repeat"
    borderColor = "IntOpaqueBlack"
    filePath = "textures/viking_room.png"
    samplerName = "basicSampler"

[[Shaders]]
    name = "EntityVertexShader"
    fileName = "./glslShaders/entity.vert.spv"
    shaderType = "VertexShader"
    entryPoint = "main"
    vertexInfo = { vertexDataFlags = ["Position", "Color", "TexCoord"] }
    uniformInfo = { uniformFlags = ["ModelMatrix", "ViewMatrix", "ProjectionMatrix"] }

[[Shaders]]
    name = "EntityFragmentShader"
    fileName = "./glslShaders/entity.frag.spv"
    shaderType = "FragmentShader"
    entryPoint = "main"
    samplerNameList = ["basicSampler"]
