[[Entities]]
    entityType = "RenderEntity"
    meshNames = ["TriangleMesh"]
    cullMode = "FrontFace"
    textureNames = []
    shaderNames = ["EntityVertexShader", "EntityFragmentShader"]

[[Meshes]]
    name = "TriangleMesh"
    filePath = "meshes/triangle.obj"

[[Textures]]
    name = "BasicTexture"
    textureType = "ImageFile"
    addressMode = "Repeat"
    borderColor = "IntOpaqueBlack"
    filePath = "textures/basic.jpg"
    samplerName = "basicSampler"

[[Shaders]]
    name = "EntityVertexShader"
    fileName = "../glslShaders/entity.vert.spv"
    shaderType = "VertexShader"
    entryPoint = "main"
    vertexInfo = { vertexDataFlags = ["Position", "Color", "TexCoord"] }
    uniformInfo = { uniformFlags = [] }

[[Shaders]]
    name = "EntityFragmentShader"
    fileName = "../glslShaders/entity.frag.spv"
    shaderType = "FragmentShader"
    entryPoint = "main"
    samplerNameList = [""]
